VERILOG_SOURCES += ../common/timescaleit.v Counter.v
TOPLEVEL=Counter
MODULE=CounterTester

#include $(COCOTB)/makefiles/Makefile.inc
#include $(COCOTB)/makefiles/Makefile.sim
include ../common/Makefile.sim
